import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { NgbDateTimepickerModule } from '@ng-bootstrap/ng-bootstrap';
import { NavMenuComponent } from './nav-menu.component';

@NgModule({
    declarations: [NavMenuComponent],
    imports: [
        CommonModule,
        FormsModule,
        NgbModule,
        NgbDateTimepickerModule
    ],
    exports: [NavMenuComponent]
})
export class NavMenuModule { }
// JavaScript source code
