import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { NgbDatepickerModule } from '@ng-bootstrap/ng-bootstrap';
import { DobComponent } from './dob.component';

@NgModule({
  declarations: [DobComponent],
  imports: [
    CommonModule,
    FormsModule,
    NgbModule,
	NgbDatepickerModule
  ],
  exports: [DobComponent]
})
export class DobModule { }
